name: ${pluginName}
version: ${version}
main: com.exanthiax.xbattlepass.XBattlePass
author: Exanthiax, _OfTeN_
api-version: 1.19
depend:
  - eco
softdepend:
  - libreforge
commands:
  xbattlepass:
    aliases: [xbp]
