display:
  display-name: "Bouncer"
  lore:
    - "&8»&7 Click wooden doors &a%required_task_xp%&7 times"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: click_block
    multiplier: 1
    filters:
      blocks:
        - "#WOODEN_DOORS"