display:
  display-name: "Beekeeper"
  lore:
    - "&8»&7 Harvest &a%required_task_xp%&7 honeycombs"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: click_block
    multiplier: 1
    filters:
      blocks:
        - BEE_NEST
        - BEEHIVE
      items:
        - "*SHEARS"
      honey_level_full: true