display:
  display-name: "Researcher"
  lore:
    - "&8»&7 Collect &a%required_task_xp%&7 experience"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: gain_xp
    multiplier: 1