display:
  display-name: "Carnivore"
  lore:
    - "&8»&7 Eat &a%required_task_xp%&7 meat"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: consume
    multiplier: 1
    filters:
      items:
        - "#ITEMS_MEAT"