display:
  display-name: "Farmer"
  lore:
    - "&8»&7 Harvest &a%required_task_xp%&7 beetroot"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "BEETROOTS"
      fully_grown: true