display:
  display-name: "Slayer"
  lore:
    - "&8»&7 Kill &a%required_task_xp%&7 blazes"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: kill
    value: 1
    filters:
      entities:
        - BLAZE
