display:
  display-name: "Why Squid?"
  lore:
    - "&8»&7 Leash &a%required_task_xp%&7 squids"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: leash_entity
    multiplier: 1
    filters:
      entities:
        - SQUID
        - GLOW_SQUID