display:
  display-name: "Logger"
  lore:
    - "&8»&7 Chop &a%required_task_xp%&7 logs"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "#LOGS"
      player_placed: false