display:
  display-name: "Glazier"
  lore:
    - "&8»&7 Place &a%required_task_xp%&7 glass blocks"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: click_block
    multiplier: 1
    filters:
      blocks:
        - GLASS