display:
  display-name: "Swimmer"
  lore:
    - "&8»&7 Swim &a%required_task_xp%&7 blocks"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: move
    multiplier: 1
    conditions:
      - id: is_swimming