display:
  display-name: "Diplomacy"
  lore:
    - "&8»&7 Vote for the server &a%required_task_xp%&7 times"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: register_vote
    value: 1
