display:
  display-name: "Chatter"
  lore:
    - "&8»&7 Send &cVictory belongs to the bold! &a%required_task_xp%&7 times"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: send_message
    multiplier: 1
    filters:
      text:
        - "Victory belongs to the bold!"