display:
  display-name: "Chatter"
  lore:
    - "&8»&7 Send &a%required_task_xp%&7 messages"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: send_message
    multiplier: 1