display:
  display-name: "Sparkle Fruit"
  lore:
    - "&8»&7 Eat &a%required_task_xp%&7 golden apples"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: consume
    multiplier: 1
    filters:
      items:
        - GOLDEN_APPLE
        - ENCHANTED_GOLDEN_APPLE