display:
  display-name: "Clumsy"
  lore:
    - "&8»&7 Take &a%required_task_xp%&7 fall damage"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: fall_damage
    multiplier: 1