display:
  display-name: "Butter Tools"
  lore:
    - "&8»&7 Break &a%required_task_xp%&7 golden tools"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: item_break
    multiplier: 1
    filters:
      items:
        - GOLDEN_AXE
        - GOLDEN_HOE
        - GOLDEN_PICKAXE
        - GOLDEN_SHOVEL
        - GOLDEN_SWORD