display:
  display-name: "Master Bargainer"
  lore:
    - "&8»&7 Earn &a%required_task_xp%&7 villager trading experience"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: villager_trade
    multiplier: 1
