display:
  display-name: "Ultimate Protector"
  lore:
    - "&8»&7 Win &a%required_task_xp%&7 raids"
    - "&8»&7 Completed: &a%current_task_xp%&7/&a%required_task_xp%"

xp-gain-methods:
  - trigger: win_raid
    value: 1
